[metadata]
name = amqtt
description = MQTT client/broker using Python asyncio
long_description = file: readme.rst
long_description_content_type = text/x-rst
license = MIT
license_files = license.txt
classifiers =
    Development Status :: 3 - Alpha,
    Intended Audience :: Developers,
    License :: OSI Approved :: MIT License
    Operating System :: MacOS,
    Operating System :: Microsoft :: Windows,
    Operating System :: POSIX,
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: Implementation :: CPython
    Topic :: Communications,
    Topic :: Internet,
authors = ["aMQTT Contributers"]
homepage = https://github.com/Yakifo/amqtt
packages =
    amqtt

[options]
packages = find:
install_requires =
    PyYAML>=5.4.0,<7.0
    docopt~=0.6.0
    passlib~=1.7.0
    transitions~=0.8.0
    websockets>=9.0,<11.0
python_requires = >=3.9
include_package_data = True

[options.entry_points]
console_scripts =
    amqtt = amqtt.scripts.broker_script:main
    amqtt_pub = amqtt.scripts.pub_script:main
    amqtt_sub = amqtt.scripts.sub_script:main
amqtt.broker.plugins =
    event_logger_plugin = amqtt.plugins.logging:EventLoggerPlugin
    packet_logger_plugin = amqtt.plugins.logging:PacketLoggerPlugin
    auth_anonymous = amqtt.plugins.authentication:AnonymousAuthPlugin
    auth_file = amqtt.plugins.authentication:FileAuthPlugin
    topic_taboo = amqtt.plugins.topic_checking:TopicTabooPlugin
    topic_acl = amqtt.plugins.topic_checking:TopicAccessControlListPlugin
    broker_sys = amqtt.plugins.sys.broker:BrokerSysPlugin
amqtt.client.plugins =
    packet_logger_plugin = amqtt.plugins.logging:PacketLoggerPlugin
amqtt.test.plugins =
    test_plugin = tests.plugins.test_manager:EmptyTestPlugin
    event_plugin = tests.plugins.test_manager:EventTestPlugin
    packet_logger_plugin = amqtt.plugins.logging:PacketLoggerPlugin

[options.extras_require]
base =
    asyncmock
    black
    flake8
    hypothesis
    mypy
    pre-commit
    psutil
    pylint
    pytest
    pytest-asyncio
    pytest-cov
    pytest-logdog
ci =
    amqtt[base]
    coveralls
dev =
    amqtt[base]
    tox

[flake8]
ignore =
    E,
    W,
    F722,
    F722
