[tox]
envlist = py39, py39, py310, py311, py312, py313
isolated_build = True
skip_missing_interpreters = True

[testenv]
description = Run tests with pytest for all pythone versions that tox can find.
setenv =
    PYTHONPATH = {toxinidir}
passenv =
    HOME
extras =
    dev
commands =
    {posargs:pytest --cov amqtt --cov tests --cov-report=term --cov-report=xml}

[testenv:{lint,lintupdate}]
description =
    lint: Run linters with pre-commit on all files.
    lintupdate: Update pre-commit hooks.
skip_install = True
deps =
    pre-commit
commands =
    lint: pre-commit run --all-files
    lintupdate: pre-commit autoupdate
